<?php

return [
    \ZanPHP\YZNsq\TOC::class => "Zan\\Framework\\Components\\Nsq\\TOC",
    \ZanPHP\YZNsq\SQS::class => "Zan\\Framework\\Components\\Nsq\\SQS",
    \ZanPHP\YZNsq\SimpleMsgHandler::class => "Zan\\Framework\\Components\\Nsq\\SimpleMsgHandler",
    \ZanPHP\YZNsq\Producer::class => "Zan\\Framework\\Components\\Nsq\\Producer",
    \ZanPHP\YZNsq\NsqException::class => "Zan\\Framework\\Components\\Nsq\\NsqException",
    \ZanPHP\YZNsq\NsqConfig::class => "Zan\\Framework\\Components\\Nsq\\NsqConfig",
    \ZanPHP\YZNsq\NopConnDelegate::class => "Zan\\Framework\\Components\\Nsq\\NopConnDelegate",
    \ZanPHP\YZNsq\MessageParam::class => "Zan\\Framework\\Components\\Nsq\\MessageParam",
    \ZanPHP\YZNsq\Message::class => "Zan\\Framework\\Components\\Nsq\\Message",
    \ZanPHP\YZNsq\Lookup::class => "Zan\\Framework\\Components\\Nsq\\Lookup",
    \ZanPHP\YZNsq\InitializeSQS::class => "Zan\\Framework\\Components\\Nsq\\InitializeSQS",
    \ZanPHP\YZNsq\Frame::class => "Zan\\Framework\\Components\\Nsq\\Frame",
    \ZanPHP\YZNsq\Consumer::class => "Zan\\Framework\\Components\\Nsq\\Consumer",
    \ZanPHP\YZNsq\ConnMsgDelegate::class => "Zan\\Framework\\Components\\Nsq\\ConnMsgDelegate",
    \ZanPHP\YZNsq\Connection::class => "Zan\\Framework\\Components\\Nsq\\Connection",
    \ZanPHP\YZNsq\Command::class => "Zan\\Framework\\Components\\Nsq\\Command",
    \ZanPHP\YZNsq\Command::class => "Zan\\Framework\\Components\\Nsq\\Command",
    \ZanPHP\YZNsq\Utils\Backoff::class => "Zan\\Framework\\Components\\Nsq\\Utils\\Backoff",
    \ZanPHP\YZNsq\Utils\Binary::class => "Zan\\Framework\\Components\\Nsq\\Utils\\Binary",
    \ZanPHP\YZNsq\Utils\Dns::class => "Zan\\Framework\\Components\\Nsq\\Utils\\Dns",
    \ZanPHP\YZNsq\Utils\Lock::class => "Zan\\Framework\\Components\\Nsq\\Utils\\Lock",
    \ZanPHP\YZNsq\Utils\MemoryBuffer::class => "Zan\\Framework\\Components\\Nsq\\Utils\\MemoryBuffer",
    \ZanPHP\YZNsq\Utils\ObjectPool::class => "Zan\\Framework\\Components\\Nsq\\Utils\\ObjectPool",
    \ZanPHP\YZNsq\Utils\SpinLock::class => "Zan\\Framework\\Components\\Nsq\\Utils\\SpinLock",
    \ZanPHP\YZNsq\Utils\StringBuffer::class => "Zan\\Framework\\Components\\Nsq\\Utils\\StringBuffer",
    \ZanPHP\YZNsq\Toc\MessageBuilder::class => "Zan\\Framework\\Components\\Nsq\\Toc\\MessageBuilder",
    \ZanPHP\YZNsq\Toc\TocException::class => "Zan\\Framework\\Components\\Nsq\\Toc\\TocException",
    \ZanPHP\YZNsq\Contract\Buffer::class => "Zan\\Framework\\Components\\Nsq\\Contract\\Buffer",
    \ZanPHP\YZNsq\Contract\ConnDelegate::class => "Zan\\Framework\\Components\\Nsq\\Contract\\ConnDelegate",
    \ZanPHP\YZNsq\Contract\MsgDelegate::class => "Zan\\Framework\\Components\\Nsq\\Contract\\MsgDelegate",
    \ZanPHP\YZNsq\Contract\MsgHandler::class => "Zan\\Framework\\Components\\Nsq\\Contract\\MsgHandler",
    \ZanPHP\YZNsq\Contract\NsqdDelegate::class => "Zan\\Framework\\Components\\Nsq\\Contract\\NsqdDelegate",
];